version: "3.9"

services:
    mongo:
        image: mongo
        container_name: gw_mongodb
        restart: unless-stopped
        ports: 
            - "27017:27017"

    client:
        build: ./client
        container_name: gw_client
        restart: always
        volumes: 
            - ./client:/src/app
        ports: 
            - "3000:3000"
        depends_on: 
            - server
        command: npm run start
   
    user:
        build: ./user_service
        container_name: gw_user
        restart: always
        environment:
            - MongoURI=mongodb://mongo:27017/user
            - JWTSecret=${JWTSecret}
        volumes: 
            - ./user_service:/src/app
        ports: 
            - "4100:4100"
        depends_on: 
            - mongo
        command: npm run server

    workout:
        build: ./workout_service
        container_name: gw_workout
        restart: always
        environment:
            - MongoURI=mongodb://mongo:27017/workout
            - JWTSecret=${JWTSecret}
        volumes: 
            - ./workout_service:/src/app
        ports: 
            - "4200:4200"
        depends_on: 
            - mongo
        command: npm run server

    riot:
        build: ./riot_service
        container_name: gw_riot
        restart: always
        environment:
            - MongoURI=mongodb://mongo:27017/riot
            - RiotApiKey=${RiotApiKey}
        volumes: 
            - ./riot_service:/src/app
        ports: 
            - "5000:5000"
        depends_on: 
            - mongo
        command: npm run server