export const authConstants = {
    LOGIN_LOADING: 'LOGIN_LOADING',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_LOADING: 'LOGOUT_LOADING',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',

    GETUSER_SUCCESS: 'GETUSER_SUCCESS',
    GETUSER_LOADING: 'GETUSER_LOADING',
    GETUSER_FAILURE: 'GETUSER_FAILURE',
}