export const workoutConstants = {
    GET_SPECIFIC_USER_LOADING: 'GET_SPECIFIC_USER_LOADING',
    GET_SPECIFIC_USER_SUCCESS: 'GET_SPECIFIC_USER_SUCCESS',
    GET_SPECIFIC_USER_FAILURE: 'GET_SPECIFIC_USER_FAILURE',

    GET_USER_WORKOUT_LOADING: 'GET_USER_WORKOUT_LOADING',
    GET_USER_WORKOUT_SUCCESS: 'GET_USER_WORKOUT_SUCCESS',
    GET_USER_WORKOUT_FAILURE: 'GET_USER_WORKOUT_FAILURE',
    
    UPDATE_WORKOUT_LOADING: 'UPDATE_WORKOUT_LOADING',
    UPDATE_WORKOUT_SUCCESS: 'UPDATE_WORKOUT_SUCCESS',
    UPDATE_WORKOUT_FAILURE: 'UPDATE_WORKOUT_FAILURE',
    
    GET_LIST_LOADING: 'GET_LIST_LOADING',
    GET_LIST_SUCCESS: 'GET_LIST_SUCCESS',
    GET_LIST_FAILURE: 'GET_LIST_FAILURE',
}
