export const userConstants = {
    GET_USERS_LOADING: 'GET_USERS_LOADING',
    GET_USERS_SUCCESS: 'GET_USER_SUCCESS',
    GET_USERS_FAILURE: 'GET_USER_SUCCESS',

    GET_USER_LOADING: 'GET_USER_LOADING',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_FAILURE: 'GET_USER_SUCCESS',

    ADD_USER_LOADING: 'ADD_USER_LOADING',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    ADD_USER_FAILURE: 'ADD_USER_FAILURE',

    UPDATE_WORKOUT_LOADING: 'UPDATE_WORKOUT_LOADING',
    UPDATE_WORKOUT_SUCCESS: 'UPDATE_WORKOUT_SUCCESS',
    UPDATE_WORKOUT_FAILURE: 'UPDATE_WORKOUT_FAILURE',
}
