export const userConstants = {
    GET_USERS_SUCCESS: 'GET_USER_SUCCESS',
    GET_USERS_FAILURE: 'GET_USER_SUCCESS',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_FAILURE: 'GET_USER_SUCCESS',
    ADD_USER_SUCCESS: 'GET_USER_SUCCESS',
    ADD_USER_FAILURE: 'GET_USER_SUCCESS',
    UPDATE_WORKOUT_SUCCESS: 'GET_USER_SUCCESS',
    UPDATE_WORKOUT_FAILURE: 'GET_USER_SUCCESS',
}
